FROM maven:3.5.4-jdk-8-alpine as step1
WORKDIR /src
COPY  . /src
RUN mvn clean package

FROM tomcat:9.0.10-jre8-alpine
COPY --from=step1 /src/target/api.war /usr/local/tomcat/webapps/

#docker image build -t deploy:0.2 -f Dockerfile_steps .
#docker container run -p 8080:8080 deploy:0.2
#http://localhost:8080/api/hello
