FROM maven:3.5.2-jdk-8-alpine as builder
WORKDIR /src
COPY settings.xml /root/.m2/settings.xml
COPY . /src
RUN mvn clean package

FROM tomcat:9.0.10-jre8-alpine
ENV DATABASE_URL="jdbc:mysql://my_database/sample?user=user01&password=password"
COPY --from=builder /src/target/api.war /usr/local/tomcat/webapps/
